name: Deploy modpack

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "deploy"
  cancel-in-progress: false

env:
  PACKWIZ_COMMIT: 0bb89a4872d8dc2c45af251345ee780cab7ab9ad
  PACKWIZ_DIR: /tmp/packwiz_artifact
  PACKWIZ: /tmp/packwiz_artifact/packwiz
  PACKWIZ_BOOTSTRAP_VERSION: "v0.0.3"

jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up dependencies

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Cache Packwiz
        id: cache-packwiz
        uses: actions/cache@v3
        with:
          path: ${{ env.PACKWIZ_DIR }}
          key: packwiz-${{ env.PACKWIZ_COMMIT }}
      - if: ${{ steps.cache-packwiz.outputs.cache-hit != 'true' }}
        name: Download Packwiz
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          repo: packwiz/packwiz
          workflow: go.yml
          name: "Linux 64-bit x86"
          path: ${{ env.PACKWIZ_DIR }}
          commit: ${{ env.PACKWIZ_COMMIT }}
      - name: Make packwiz executable
        run: chmod +x ${{ env.PACKWIZ }}

      # Build

      - name: Build pack
        run: python scripts/assemble_packwiz.py

      # Test
      # - name: Cache Packwiz Bootstrap
      #   uses: actions/cache@v3
      #   with:
      #     path: run/packwiz-installer
      #     key: packwiz-bootstrap-${{ env.PACKWIZ_BOOTSTRAP_VERSION }}
      # - uses: actions/setup-java@v4
      #   with:
      #     distribution: 'temurin' # See 'Supported distributions' for available options
      #     java-version: '21'
      # - name: Test pack
      #   run: python scripts/run_test.py

      # Deploy

      - name: ðŸ¤³ Deploy website
        uses: XPH0816/webdav-deploy-action@v0.3
        with:
          url: https://theepicblock.nl/
          username: modfestghci
          password: ${{ secrets.TEB_WEBDAV_PASSWORD }}
          local: "./generated/pack/"
          remote: "private/ModFest-1-21"